### ISSUE TITLE
Deploy package through Travis-CI automatically

### ISSUE THREAD

**Issue by Sylhare** [Sylhare/nprime#12]
The goal is to follow the process and push to Pypi automatically

- https://docs.travis-ci.com/user/deployment/pypi/

```yaml
deploy:
  provider: pypi
  user: "Your username"
  password: "Your password"
```

With obviously the password [encrypted](https://docs.travis-ci.com/user/encryption-keys/) using the travis gem 
```
gem install travis
```

Then

```bash
travis encrypt --add deploy.password
```
